//! Common types for video processing HTTP clients.

use serde::{Deserialize, Serialize};

/// Represents a detected scene boundary in a video.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SceneBoundary {
    /// Zero-based index of the scene.
    pub scene_index: u32,
    /// Start timestamp in milliseconds.
    pub start_ms: u64,
    /// End timestamp in milliseconds.
    pub end_ms: u64,
    /// Whether this boundary was detected by content analysis (true)
    /// or generated by fallback interval (false).
    pub is_detected: bool,
}

impl SceneBoundary {
    /// Creates a new scene boundary.
    #[must_use]
    pub const fn new(scene_index: u32, start_ms: u64, end_ms: u64, is_detected: bool) -> Self {
        Self {
            scene_index,
            start_ms,
            end_ms,
            is_detected,
        }
    }

    /// Returns the duration of this scene in milliseconds.
    #[must_use]
    pub const fn duration_ms(&self) -> u64 {
        self.end_ms.saturating_sub(self.start_ms)
    }

    /// Returns the midpoint timestamp of this scene in milliseconds.
    #[must_use]
    pub const fn mid_ms(&self) -> u64 {
        self.start_ms + self.duration_ms() / 2
    }
}

/// Represents a transcript segment with timing information.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TranscriptSegment {
    /// Start timestamp in milliseconds.
    pub start_ms: u64,
    /// End timestamp in milliseconds.
    pub end_ms: u64,
    /// The transcribed text content.
    pub text: String,
    /// Optional confidence score (0.0 to 1.0).
    pub confidence: Option<f32>,
}

impl TranscriptSegment {
    /// Creates a new transcript segment.
    #[must_use]
    pub fn new(
        start_ms: u64,
        end_ms: u64,
        text: impl Into<String>,
        confidence: Option<f32>,
    ) -> Self {
        Self {
            start_ms,
            end_ms,
            text: text.into(),
            confidence,
        }
    }

    /// Returns the duration of this segment in milliseconds.
    #[must_use]
    pub const fn duration_ms(&self) -> u64 {
        self.end_ms.saturating_sub(self.start_ms)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_scene_boundary_new() {
        let scene = SceneBoundary::new(0, 0, 5000, true);
        assert_eq!(scene.scene_index, 0);
        assert_eq!(scene.start_ms, 0);
        assert_eq!(scene.end_ms, 5000);
        assert!(scene.is_detected);
    }

    #[test]
    fn test_scene_boundary_duration_ms() {
        let scene = SceneBoundary::new(1, 1000, 6000, true);
        assert_eq!(scene.duration_ms(), 5000);
    }

    #[test]
    fn test_scene_boundary_duration_ms_saturating() {
        // Edge case: start > end (should not happen, but should not panic)
        let scene = SceneBoundary::new(0, 5000, 1000, false);
        assert_eq!(scene.duration_ms(), 0);
    }

    #[test]
    fn test_scene_boundary_mid_ms() {
        let scene = SceneBoundary::new(0, 1000, 5000, true);
        // Duration is 4000, mid is 1000 + 2000 = 3000
        assert_eq!(scene.mid_ms(), 3000);
    }

    #[test]
    fn test_scene_boundary_mid_ms_odd_duration() {
        let scene = SceneBoundary::new(0, 0, 5001, true);
        // Duration is 5001, mid is 0 + 2500 = 2500 (integer division)
        assert_eq!(scene.mid_ms(), 2500);
    }

    #[test]
    fn test_scene_boundary_serialize() {
        let scene = SceneBoundary::new(2, 10000, 15000, false);
        let json = serde_json::to_string(&scene).unwrap();
        assert!(json.contains("\"scene_index\":2"));
        assert!(json.contains("\"start_ms\":10000"));
        assert!(json.contains("\"end_ms\":15000"));
        assert!(json.contains("\"is_detected\":false"));
    }

    #[test]
    fn test_scene_boundary_deserialize() {
        let json = r#"{"scene_index":1,"start_ms":5000,"end_ms":10000,"is_detected":true}"#;
        let scene: SceneBoundary = serde_json::from_str(json).unwrap();
        assert_eq!(scene.scene_index, 1);
        assert_eq!(scene.start_ms, 5000);
        assert_eq!(scene.end_ms, 10000);
        assert!(scene.is_detected);
    }

    #[test]
    fn test_transcript_segment_new() {
        let segment = TranscriptSegment::new(0, 2000, "Hello world", Some(0.95));
        assert_eq!(segment.start_ms, 0);
        assert_eq!(segment.end_ms, 2000);
        assert_eq!(segment.text, "Hello world");
        assert_eq!(segment.confidence, Some(0.95));
    }

    #[test]
    fn test_transcript_segment_new_no_confidence() {
        let segment = TranscriptSegment::new(1000, 3000, "Test text", None);
        assert_eq!(segment.start_ms, 1000);
        assert_eq!(segment.end_ms, 3000);
        assert_eq!(segment.text, "Test text");
        assert_eq!(segment.confidence, None);
    }

    #[test]
    fn test_transcript_segment_duration_ms() {
        let segment = TranscriptSegment::new(1000, 4000, "Test", None);
        assert_eq!(segment.duration_ms(), 3000);
    }

    #[test]
    fn test_transcript_segment_duration_ms_saturating() {
        let segment = TranscriptSegment::new(5000, 1000, "Test", None);
        assert_eq!(segment.duration_ms(), 0);
    }

    #[test]
    fn test_transcript_segment_serialize() {
        let segment = TranscriptSegment::new(0, 1000, "Hello", Some(0.9));
        let json = serde_json::to_string(&segment).unwrap();
        assert!(json.contains("\"start_ms\":0"));
        assert!(json.contains("\"end_ms\":1000"));
        assert!(json.contains("\"text\":\"Hello\""));
        assert!(json.contains("\"confidence\":0.9"));
    }

    #[test]
    fn test_transcript_segment_deserialize() {
        let json = r#"{"start_ms":500,"end_ms":1500,"text":"World","confidence":null}"#;
        let segment: TranscriptSegment = serde_json::from_str(json).unwrap();
        assert_eq!(segment.start_ms, 500);
        assert_eq!(segment.end_ms, 1500);
        assert_eq!(segment.text, "World");
        assert_eq!(segment.confidence, None);
    }

    #[test]
    fn test_scene_boundary_clone() {
        let scene = SceneBoundary::new(0, 0, 1000, true);
        let cloned = scene.clone();
        assert_eq!(scene, cloned);
    }

    #[test]
    fn test_transcript_segment_clone() {
        let segment = TranscriptSegment::new(0, 1000, "Test", Some(0.8));
        let cloned = segment.clone();
        assert_eq!(segment, cloned);
    }

    #[test]
    fn test_scene_boundary_debug() {
        let scene = SceneBoundary::new(0, 0, 1000, true);
        let debug = format!("{scene:?}");
        assert!(debug.contains("SceneBoundary"));
        assert!(debug.contains("scene_index: 0"));
    }

    #[test]
    fn test_transcript_segment_debug() {
        let segment = TranscriptSegment::new(0, 1000, "Test", Some(0.8));
        let debug = format!("{segment:?}");
        assert!(debug.contains("TranscriptSegment"));
        assert!(debug.contains("text: \"Test\""));
    }
}
