apiVersion: v1
kind: Service
metadata:
  name: reranker-service
  namespace: llm-serving
  labels:
    app: reranker-service
spec:
  selector:
    app: reranker-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
