#!/usr/bin/env python3
"""Generate Prometheus SLO recording and alerting rules from Python definitions.

Usage:
    python scripts/generate_slo_rules.py --output-dir config/prometheus/

This script reads the SLI/SLO definitions from the shared observability module
and generates Prometheus-compatible YAML rule files.
"""

import argparse
import sys
from pathlib import Path

# Add services directory to path for imports
repo_root = Path(__file__).parent.parent
sys.path.insert(0, str(repo_root / "services"))

import yaml  # noqa: E402


def main() -> int:
    """Generate SLO rules and write to output directory."""
    parser = argparse.ArgumentParser(
        description="Generate Prometheus SLO recording and alerting rules"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("config/prometheus"),
        help="Output directory for generated YAML files",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print rules to stdout instead of writing files",
    )
    args = parser.parse_args()

    # Import after path setup
    from shared.observability.metrics.definitions.slo import (
        SLO_CATALOG,
        generate_all_slo_rules,
    )

    print(f"Generating rules for {len(SLO_CATALOG)} SLOs...")

    rules = generate_all_slo_rules()

    # Split into recording and alerting groups
    recording_group = next(
        (g for g in rules["groups"] if g["name"] == "slo_recording_rules"),
        {"name": "slo_recording_rules", "interval": "30s", "rules": []},
    )
    alerting_group = next(
        (g for g in rules["groups"] if g["name"] == "slo_alerting_rules"),
        {"name": "slo_alerting_rules", "rules": []},
    )

    recording_rules = {"groups": [recording_group]}
    alerting_rules = {"groups": [alerting_group]}

    if args.dry_run:
        print("\n=== Recording Rules ===")
        print(yaml.dump(recording_rules, default_flow_style=False, sort_keys=False))
        print("\n=== Alerting Rules ===")
        print(yaml.dump(alerting_rules, default_flow_style=False, sort_keys=False))
        return 0

    # Create output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Write recording rules
    recording_path = args.output_dir / "slo_recording_rules.yaml"
    with open(recording_path, "w") as f:
        f.write("# Auto-generated by scripts/generate_slo_rules.py\n")
        f.write("# DO NOT EDIT MANUALLY - changes will be overwritten\n\n")
        yaml.dump(recording_rules, f, default_flow_style=False, sort_keys=False)
    print(f"Wrote recording rules to {recording_path}")

    # Write alerting rules
    alerting_path = args.output_dir / "slo_alerting_rules.yaml"
    with open(alerting_path, "w") as f:
        f.write("# Auto-generated by scripts/generate_slo_rules.py\n")
        f.write("# DO NOT EDIT MANUALLY - changes will be overwritten\n\n")
        yaml.dump(alerting_rules, f, default_flow_style=False, sort_keys=False)
    print(f"Wrote alerting rules to {alerting_path}")

    print(f"\nGenerated {len(recording_group['rules'])} recording rules")
    print(f"Generated {len(alerting_group['rules'])} alerting rules")

    return 0


if __name__ == "__main__":
    sys.exit(main())
