apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: llm-serving
  labels:
    app: embedding-service
spec:
  selector:
    app: embedding-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
